start_request_validator_responses = {
    201: {
        "description": "Success",
        "content": {
            "application/json": {
                "examples": {
                    "Normal": {"value": {
                                  "esito": "Processo di ESEGUI_TUTTO_CON_REPORT RUNNING",
                                  "validator_request": {
                                    "Request": {
                                      "ID": "1",
                                      "SHAPEFILE": "Shape_flat.zip",
                                      "STATO": "uploaded",
                                      "STATUS": "RUNNING",
                                      "USER_ID": "giu",
                                      "GROUP_ID": "tim",
                                      "DATA_CARICAMENTO": "2024-02-21 09:39:38.940966",
                                      "DATA_ELABORAZIONE": None,
                                      "DATA_VALIDAZIONE": None,
                                      "PATH_SHAPEFILE": "to_upload/Shape_flat20240221_0939/Shape_flat",
                                      "MD5": "da3a0981a7cfe5fb25ffc921823568ce",
                                      "HOST_WORKER": "test",
                                      "RUNNING": None,
                                      "QUEUED": None,
                                      "ESITO": None,
                                      "STACK_TRACE_JAVA": None,
                                      "RESULTS": None,
                                      "USERFILE": None,
                                      "SINFI_PLUS": None
                                    }
                                  }
                                }
                   },
                   "Queued": {"value": {
                              "esito": "Processo di ESEGUI_TUTTO_CON_REPORT RUNNING",
                              "validator_request": {
                                "Request": {
                                  "ID": "2",
                                  "SHAPEFILE": "Shape_flat.zip",
                                  "STATO": "uploaded",
                                  "STATUS": "QUEUED",
                                  "USER_ID": "giu",
                                  "GROUP_ID": "tim",
                                  "DATA_CARICAMENTO": "2024-02-15 14:24:29.873938",
                                  "PATH_SHAPEFILE": "to_upload/Shape_flat20240215_1424/Shape_flat",
                                  "MD5": "da3a0981a7cfe5fb25ffc921823568ce",
                                  "HOST_WORKER": "test",
                                  "RUNNING": None,
                                  "QUEUED": None,
                                  "ESITO": None,
                                  "STACK_TRACE_JAVA": None,
                                  "RESULTS": None,
                                  "USERFILE": None,
                                  "DATA_ELABORAZIONE": None
                                }
                              }
                            }
                },
            }
        },}
    },
    501 : {
        "description": "Bad request",
        "content": {
            "application/json": {
                "example": {
                        "error": "[WinError 1225] Il computer remoto ha rifiutato la connessione di rete",
                      "group_id": "tim",
                      "path": None
                }
            }
        },
    }
}

resp_load_shapefile2postgis = {
    201: {
        "description": "Success",
        "content": {
            "application/json": {
                "example": {
                    "result": {
                        "to_upload\\shpesempio\\antenne.csv": "antenne",
                        "Stats": {
                            "antenne": "to_upload\\shpesempio\\antenne.csv elapsed:0.289592",
                            "comuni": "to_upload\\shpesempio\\comune\\comuni.shp elapsed:0.649969",
                            "condotte": "to_upload\\shpesempio\\condotte\\condotte.shp elapsed:16.974856",
                            "giunzione": "to_upload\\shpesempio\\giunzione\\giunzione.shp elapsed:2.951051",
                            "TOTAL": "Total time elapsed:40.077794",
                        },
                        "to_upload\\shpesempio\\comune\\comuni.shp": "comuni",
                        "to_upload\\shpesempio\\condotte\\condotte.shp": "condotte",
                        "to_upload\\shpesempio\\giunzione\\giunzione.shp": "giunzione",
                    },
                    "esito": "OK",
                    "layers": {
                        "to_upload\\shpesempio\\antenne.csv": "antenne",
                        "Stats": {
                            "antenne": "to_upload\\shpesempio\\antenne.csv elapsed:0.289592",
                            "comuni": "to_upload\\shpesempio\\comune\\comuni.shp elapsed:0.649969",
                            "condotte": "to_upload\\shpesempio\\condotte\\condotte.shp elapsed:16.974856",
                            "giunzione": "to_upload\\shpesempio\\giunzione\\giunzione.shp elapsed:2.951051",
                            "TOTAL": "Total time elapsed:40.077794",
                        },
                        "to_upload\\shpesempio\\comune\\comuni.shp": "comuni",
                        "to_upload\\shpesempio\\condotte\\condotte.shp": "condotte",
                        "to_upload\\shpesempio\\giunzione\\giunzione.shp": "giunzione",
                    },
                }
            }
        },
    },
    501: {
        "description": "Bad request",
        "content": {
            "application/json": {
                "example": {"error": "Error", "group_id": "group_id", "id": "id"}
            }
        },
    },
}

resp_load_zip = {
    201: {
        "description": "Success",
        "content": {
            "application/json": {
                "example": {
                    "data": [
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "comune",
                            "tipo": "text",
                            "column_name": "comune",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "provincia",
                            "tipo": "text",
                            "column_name": "provincia",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "regione",
                            "tipo": "text",
                            "column_name": "regione",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "nome",
                            "tipo": "text",
                            "column_name": "nome",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "anno_inserimento",
                            "tipo": "integer",
                            "column_name": "anno_inserimento",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "data_e_ora_inserimento",
                            "tipo": "text",
                            "column_name": "data_e_ora_inserimento",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "identificatore_in_openstreetmap",
                            "tipo": "integer",
                            "column_name": "identificatore_in_openstreetmap",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "longitudine",
                            "tipo": "double precision",
                            "column_name": "longitudine",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "latitudine",
                            "tipo": "double precision",
                            "column_name": "latitudine",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "group_id",
                            "tipo": "text",
                            "column_name": "group_id",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\antenne.csv",
                            "schema_name": "test",
                            "table": "antenne",
                            "column": "geometry",
                            "tipo": "geometry(Point,4326)",
                            "column_name": "geometry",
                            "importing": True,
                            "isVariable": False,
                            "srid": 0,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "id",
                            "tipo": "integer",
                            "column_name": "id",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cod_rip",
                            "tipo": "double precision",
                            "column_name": "cod_rip",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cod_reg",
                            "tipo": "double precision",
                            "column_name": "cod_reg",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cod_prov",
                            "tipo": "double precision",
                            "column_name": "cod_prov",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cod_cm",
                            "tipo": "double precision",
                            "column_name": "cod_cm",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cod_uts",
                            "tipo": "double precision",
                            "column_name": "cod_uts",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "pro_com",
                            "tipo": "double precision",
                            "column_name": "pro_com",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "istat",
                            "tipo": "text",
                            "column_name": "istat",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "comune",
                            "tipo": "text",
                            "column_name": "comune",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "comune_a",
                            "tipo": "text",
                            "column_name": "comune_a",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "cc_uts",
                            "tipo": "double precision",
                            "column_name": "cc_uts",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "shape_leng",
                            "tipo": "double precision",
                            "column_name": "shape_leng",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "settore",
                            "tipo": "text",
                            "column_name": "settore",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "geometry",
                            "tipo": "geometry(MultiPolygon,32633)",
                            "column_name": "geometry",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\comune\\comuni.shp",
                            "schema_name": "test",
                            "table": "comuni",
                            "column": "group_id",
                            "tipo": "text",
                            "column_name": "group_id",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "gid",
                            "tipo": "integer",
                            "column_name": "gid",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "unid",
                            "tipo": "text",
                            "column_name": "unid",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "unid_from",
                            "tipo": "text",
                            "column_name": "unid_from",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "unid_to",
                            "tipo": "text",
                            "column_name": "unid_to",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "lunghezza",
                            "tipo": "double precision",
                            "column_name": "lunghezza",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "diametro_n",
                            "tipo": "double precision",
                            "column_name": "diametro_n",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "diametro",
                            "tipo": "double precision",
                            "column_name": "diametro",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "stato",
                            "tipo": "text",
                            "column_name": "stato",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "materiale",
                            "tipo": "text",
                            "column_name": "materiale",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "cod_sezion",
                            "tipo": "text",
                            "column_name": "cod_sezion",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "sn_protezi",
                            "tipo": "text",
                            "column_name": "sn_protezi",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "funzione",
                            "tipo": "text",
                            "column_name": "funzione",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "manto",
                            "tipo": "text",
                            "column_name": "manto",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "funzioname",
                            "tipo": "text",
                            "column_name": "funzioname",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "profondita",
                            "tipo": "double precision",
                            "column_name": "profondita",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "raggiungib",
                            "tipo": "text",
                            "column_name": "raggiungib",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "tipo_posa",
                            "tipo": "text",
                            "column_name": "tipo_posa",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "interferen",
                            "tipo": "text",
                            "column_name": "interferen",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "posizione",
                            "tipo": "text",
                            "column_name": "posizione",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "espropriat",
                            "tipo": "text",
                            "column_name": "espropriat",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "precedente",
                            "tipo": "text",
                            "column_name": "precedente",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "comune",
                            "tipo": "text",
                            "column_name": "comune",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "unid_serba",
                            "tipo": "text",
                            "column_name": "unid_serba",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "note",
                            "tipo": "text",
                            "column_name": "note",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "data_rilie",
                            "tipo": "text",
                            "column_name": "data_rilie",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "data_ultim",
                            "tipo": "text",
                            "column_name": "data_ultim",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "cod_squadr",
                            "tipo": "text",
                            "column_name": "cod_squadr",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "esercizio",
                            "tipo": "text",
                            "column_name": "esercizio",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "informazio",
                            "tipo": "text",
                            "column_name": "informazio",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "data_aggio",
                            "tipo": "text",
                            "column_name": "data_aggio",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "unid_distr",
                            "tipo": "text",
                            "column_name": "unid_distr",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "istat",
                            "tipo": "text",
                            "column_name": "istat",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "sede_gesti",
                            "tipo": "text",
                            "column_name": "sede_gesti",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "origine_da",
                            "tipo": "text",
                            "column_name": "origine_da",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "geometry",
                            "tipo": "geometry(LineString,32633)",
                            "column_name": "geometry",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\condotte\\condotte.shp",
                            "schema_name": "test",
                            "table": "condotte",
                            "column": "group_id",
                            "tipo": "text",
                            "column_name": "group_id",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "gid",
                            "tipo": "integer",
                            "column_name": "gid",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "unid",
                            "tipo": "text",
                            "column_name": "unid",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "quota",
                            "tipo": "double precision",
                            "column_name": "quota",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "raggiungib",
                            "tipo": "text",
                            "column_name": "raggiungib",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "superficie",
                            "tipo": "text",
                            "column_name": "superficie",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "materiale",
                            "tipo": "text",
                            "column_name": "materiale",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "tipo_giunz",
                            "tipo": "text",
                            "column_name": "tipo_giunz",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "diametro_1",
                            "tipo": "text",
                            "column_name": "diametro_1",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "diametro_2",
                            "tipo": "double precision",
                            "column_name": "diametro_2",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "diametro_3",
                            "tipo": "double precision",
                            "column_name": "diametro_3",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "diametro_4",
                            "tipo": "double precision",
                            "column_name": "diametro_4",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "note",
                            "tipo": "text",
                            "column_name": "note",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "data_rilie",
                            "tipo": "text",
                            "column_name": "data_rilie",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "data_ultim",
                            "tipo": "text",
                            "column_name": "data_ultim",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "cod_squadr",
                            "tipo": "text",
                            "column_name": "cod_squadr",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "informazio",
                            "tipo": "text",
                            "column_name": "informazio",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "data_aggio",
                            "tipo": "text",
                            "column_name": "data_aggio",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "sede_gesti",
                            "tipo": "text",
                            "column_name": "sede_gesti",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "origine_da",
                            "tipo": "text",
                            "column_name": "origine_da",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "istat",
                            "tipo": "text",
                            "column_name": "istat",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "geometry",
                            "tipo": "geometry(PointZ,32633)",
                            "column_name": "geometry",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                        {
                            "filename": "to_upload\\shpesempio\\giunzione\\giunzione.shp",
                            "schema_name": "test",
                            "table": "giunzione",
                            "column": "group_id",
                            "tipo": "text",
                            "column_name": "group_id",
                            "importing": True,
                            "isVariable": False,
                            "srid": 32633,
                            "df_out": False,
                        },
                    ]
                }
            }
        }
    }
}
